// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL: conexión directa (sin pgbouncer) — requerida por Prisma CLI para migraciones
    // DATABASE_URL (con pgbouncer=true) es usada por PrismaClient en runtime
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
